[package]
name = "fu740-hal"
version = "0.1.0"
edition = "2018"

[dependencies]
fu740-pac = { path = "../fu740-pac" }
embedded-hal = { version = "0.2.3", features = ["unproven"] }
nb = "0.1.2"
riscv = "0.7.0"
